/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteRouteImport } from './routes/$site'
import { Route as SpecRouteImport } from './routes/spec'
import { Route as SiteIndexRouteImport } from './routes/$site/index'
import { Route as SiteActivityRouteImport } from './routes/$site/activity'
import { Route as SiteBidRouteImport } from './routes/$site/bid'
import { Route as SiteContactRouteImport } from './routes/$site/contact'
import { Route as SitePrivacyRouteImport } from './routes/$site/privacy'
import { Route as SiteRefundRouteImport } from './routes/$site/refund'
import { Route as SiteRulesRouteImport } from './routes/$site/rules'
import { Route as SiteTermsRouteImport } from './routes/$site/terms'
import { Route as ApiFaviconRouteImport } from './routes/api/favicon'
import { Route as SiteCheckoutOrderIdRouteImport } from './routes/$site/checkout.$orderId'
import { Route as SiteListingIdRouteImport } from './routes/$site/listing.$id'
import { Route as SiteManageTokenRouteImport } from './routes/$site/manage.$token'
import { Route as ApiWebhooksCashfreeRouteImport } from './routes/api/webhooks/cashfree'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/$site',
  path: '/$site',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecRoute = SpecRouteImport.update({
  id: '/spec',
  path: '/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteActivityRoute = SiteActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBidRoute = SiteBidRouteImport.update({
  id: '/bid',
  path: '/bid',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRefundRoute = SiteRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRulesRoute = SiteRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const ApiFaviconRoute = ApiFaviconRouteImport.update({
  id: '/api/favicon',
  path: '/api/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteCheckoutOrderIdRoute = SiteCheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => SiteRoute,
} as any)
const SiteListingIdRoute = SiteListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => SiteRoute,
} as any)
const SiteManageTokenRoute = SiteManageTokenRouteImport.update({
  id: '/manage/$token',
  path: '/manage/$token',
  getParentRoute: () => SiteRoute,
} as any)
const ApiWebhooksCashfreeRoute = ApiWebhooksCashfreeRouteImport.update({
  id: '/api/webhooks/cashfree',
  path: '/api/webhooks/cashfree',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$site': typeof SiteRouteWithChildren
  '/spec': typeof SpecRoute
  '/$site/activity': typeof SiteActivityRoute
  '/$site/bid': typeof SiteBidRoute
  '/$site/contact': typeof SiteContactRoute
  '/$site/privacy': typeof SitePrivacyRoute
  '/$site/refund': typeof SiteRefundRoute
  '/$site/rules': typeof SiteRulesRoute
  '/$site/terms': typeof SiteTermsRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/$site/': typeof SiteIndexRoute
  '/$site/checkout/$orderId': typeof SiteCheckoutOrderIdRoute
  '/$site/listing/$id': typeof SiteListingIdRoute
  '/$site/manage/$token': typeof SiteManageTokenRoute
  '/api/webhooks/cashfree': typeof ApiWebhooksCashfreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spec': typeof SpecRoute
  '/$site/activity': typeof SiteActivityRoute
  '/$site/bid': typeof SiteBidRoute
  '/$site/contact': typeof SiteContactRoute
  '/$site/privacy': typeof SitePrivacyRoute
  '/$site/refund': typeof SiteRefundRoute
  '/$site/rules': typeof SiteRulesRoute
  '/$site/terms': typeof SiteTermsRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/$site': typeof SiteIndexRoute
  '/$site/checkout/$orderId': typeof SiteCheckoutOrderIdRoute
  '/$site/listing/$id': typeof SiteListingIdRoute
  '/$site/manage/$token': typeof SiteManageTokenRoute
  '/api/webhooks/cashfree': typeof ApiWebhooksCashfreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$site': typeof SiteRouteWithChildren
  '/spec': typeof SpecRoute
  '/$site/activity': typeof SiteActivityRoute
  '/$site/bid': typeof SiteBidRoute
  '/$site/contact': typeof SiteContactRoute
  '/$site/privacy': typeof SitePrivacyRoute
  '/$site/refund': typeof SiteRefundRoute
  '/$site/rules': typeof SiteRulesRoute
  '/$site/terms': typeof SiteTermsRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/$site/': typeof SiteIndexRoute
  '/$site/checkout/$orderId': typeof SiteCheckoutOrderIdRoute
  '/$site/listing/$id': typeof SiteListingIdRoute
  '/$site/manage/$token': typeof SiteManageTokenRoute
  '/api/webhooks/cashfree': typeof ApiWebhooksCashfreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$site'
    | '/spec'
    | '/$site/activity'
    | '/$site/bid'
    | '/$site/contact'
    | '/$site/privacy'
    | '/$site/refund'
    | '/$site/rules'
    | '/$site/terms'
    | '/api/favicon'
    | '/$site/'
    | '/$site/checkout/$orderId'
    | '/$site/listing/$id'
    | '/$site/manage/$token'
    | '/api/webhooks/cashfree'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/spec'
    | '/$site/activity'
    | '/$site/bid'
    | '/$site/contact'
    | '/$site/privacy'
    | '/$site/refund'
    | '/$site/rules'
    | '/$site/terms'
    | '/api/favicon'
    | '/$site'
    | '/$site/checkout/$orderId'
    | '/$site/listing/$id'
    | '/$site/manage/$token'
    | '/api/webhooks/cashfree'
  id:
    | '__root__'
    | '/'
    | '/$site'
    | '/spec'
    | '/$site/activity'
    | '/$site/bid'
    | '/$site/contact'
    | '/$site/privacy'
    | '/$site/refund'
    | '/$site/rules'
    | '/$site/terms'
    | '/api/favicon'
    | '/$site/'
    | '/$site/checkout/$orderId'
    | '/$site/listing/$id'
    | '/$site/manage/$token'
    | '/api/webhooks/cashfree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SiteRoute: typeof SiteRouteWithChildren
  SpecRoute: typeof SpecRoute
  ApiFaviconRoute: typeof ApiFaviconRoute
  ApiWebhooksCashfreeRoute: typeof ApiWebhooksCashfreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$site': {
      id: '/$site'
      path: '/$site'
      fullPath: '/$site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec': {
      id: '/spec'
      path: '/spec'
      fullPath: '/spec'
      preLoaderRoute: typeof SpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$site/': {
      id: '/$site/'
      path: '/'
      fullPath: '/$site/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/$site/activity': {
      id: '/$site/activity'
      path: '/activity'
      fullPath: '/$site/activity'
      preLoaderRoute: typeof SiteActivityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/$site/bid': {
      id: '/$site/bid'
      path: '/bid'
      fullPath: '/$site/bid'
      preLoaderRoute: typeof SiteBidRouteImport
      parentRoute: typeof SiteRoute
    }
    '/$site/contact': {
      id: '/$site/contact'
      path: '/contact'
      fullPath: '/$site/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/$site/privacy': {
      id: '/$site/privacy'
      path: '/privacy'
      fullPath: '/$site/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/$site/refund': {
      id: '/$site/refund'
      path: '/refund'
      fullPath: '/$site/refund'
      preLoaderRoute: typeof SiteRefundRouteImport
      parentRoute: typeof SiteRoute
    }
    '/$site/rules': {
      id: '/$site/rules'
      path: '/rules'
      fullPath: '/$site/rules'
      preLoaderRoute: typeof SiteRulesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/$site/terms': {
      id: '/$site/terms'
      path: '/terms'
      fullPath: '/$site/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/favicon': {
      id: '/api/favicon'
      path: '/api/favicon'
      fullPath: '/api/favicon'
      preLoaderRoute: typeof ApiFaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$site/checkout/$orderId': {
      id: '/$site/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/$site/checkout/$orderId'
      preLoaderRoute: typeof SiteCheckoutOrderIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/$site/listing/$id': {
      id: '/$site/listing/$id'
      path: '/listing/$id'
      fullPath: '/$site/listing/$id'
      preLoaderRoute: typeof SiteListingIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/$site/manage/$token': {
      id: '/$site/manage/$token'
      path: '/manage/$token'
      fullPath: '/$site/manage/$token'
      preLoaderRoute: typeof SiteManageTokenRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/webhooks/cashfree': {
      id: '/api/webhooks/cashfree'
      path: '/api/webhooks/cashfree'
      fullPath: '/api/webhooks/cashfree'
      preLoaderRoute: typeof ApiWebhooksCashfreeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteChildren {
  SiteActivityRoute: typeof SiteActivityRoute
  SiteBidRoute: typeof SiteBidRoute
  SiteContactRoute: typeof SiteContactRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteRefundRoute: typeof SiteRefundRoute
  SiteRulesRoute: typeof SiteRulesRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteCheckoutOrderIdRoute: typeof SiteCheckoutOrderIdRoute
  SiteListingIdRoute: typeof SiteListingIdRoute
  SiteManageTokenRoute: typeof SiteManageTokenRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteActivityRoute: SiteActivityRoute,
  SiteBidRoute: SiteBidRoute,
  SiteContactRoute: SiteContactRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteRefundRoute: SiteRefundRoute,
  SiteRulesRoute: SiteRulesRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteCheckoutOrderIdRoute: SiteCheckoutOrderIdRoute,
  SiteListingIdRoute: SiteListingIdRoute,
  SiteManageTokenRoute: SiteManageTokenRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SiteRoute: SiteRouteWithChildren,
  SpecRoute: SpecRoute,
  ApiFaviconRoute: ApiFaviconRoute,
  ApiWebhooksCashfreeRoute: ApiWebhooksCashfreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
