/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiFaviconRouteImport } from './routes/api/favicon'
import { Route as ApiWebhooksCashfreeRouteImport } from './routes/api/webhooks/cashfree'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaviconRoute = ApiFaviconRouteImport.update({
  id: '/api/favicon',
  path: '/api/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksCashfreeRoute = ApiWebhooksCashfreeRouteImport.update({
  id: '/api/webhooks/cashfree',
  path: '/api/webhooks/cashfree',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/webhooks/cashfree': typeof ApiWebhooksCashfreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/webhooks/cashfree': typeof ApiWebhooksCashfreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/webhooks/cashfree': typeof ApiWebhooksCashfreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/api/favicon'
    | '/api/webhooks/cashfree'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/api/favicon'
    | '/api/webhooks/cashfree'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/api/favicon'
    | '/api/webhooks/cashfree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  ApiFaviconRoute: typeof ApiFaviconRoute
  ApiWebhooksCashfreeRoute: typeof ApiWebhooksCashfreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favicon': {
      id: '/api/favicon'
      path: '/api/favicon'
      fullPath: '/api/favicon'
      preLoaderRoute: typeof ApiFaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/cashfree': {
      id: '/api/webhooks/cashfree'
      path: '/api/webhooks/cashfree'
      fullPath: '/api/webhooks/cashfree'
      preLoaderRoute: typeof ApiWebhooksCashfreeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  ApiFaviconRoute: ApiFaviconRoute,
  ApiWebhooksCashfreeRoute: ApiWebhooksCashfreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
